export const games = [
  {
    name: 'katsaii_witchwanda',
    config: {
      config_version: 1,
      game_name: 'Witch Wanda',
      creator_name: 'Katsaii & Mashmerlow',
      prompt: 'CRAFT',
      init_room: 'katsaii_witchwanda_rm',
      view_width: 1,
      view_height: 1,
      time_seconds: 7,
      music_track: 'katsaii_witchwanda_mu',
      music_loops: false,
      interpolation_on: true,
      cartridge_col_primary: [
        198,
        119,
        95,
      ],
      cartridge_col_secondary: [
        238,
        199,
        138,
      ],
      cartridge_label: 'katsaii_witchwanda_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'Katsaii',
        'Mashmerlow',
      ],
      date_added: {
        day: 9,
        month: 'July',
        year: 2021,
      },
    },
  },
  {
    name: 'makoren_conjurer',
    config: {
      config_version: 1,
      game_name: 'Conjurer',
      creator_name: 'Makoren',
      prompt: 'MATCH',
      init_room: 'makoren_conjurer_rm_main',
      view_width: 120,
      view_height: 80,
      time_seconds: 8,
      music_track: 'sng_ennway_bit_battle',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        153,
        102,
        255,
      ],
      cartridge_col_secondary: [
        69,
        41,
        95,
      ],
      cartridge_label: 'makoren_conjurer_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: [
        'Makoren',
      ],
      date_added: '21/07/10',
    },
  },
  {
    name: 'kilomatter_jaywalker',
    config: {
      config_version: 1,
      game_name: 'Jay Walker',
      creator_name: 'Kilomatter',
      prompt: 'CROSS',
      init_room: 'kilo_jaywalker_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 6,
      music_track: 'sng_zandy_doctor',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        164,
        70,
        89,
      ],
      cartridge_col_secondary: [
        123,
        23,
        62,
      ],
      cartridge_label: 'kilo_jaywalker_sprCartLabel',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'Kilomatter',
        'Zandy',
      ],
      date_added: '21/08/17',
      is_enabled: true,
    },
  },
  {
    name: 'space_rocket_lander',
    config: {
      config_version: 1,
      game_name: 'Rocket Lander',
      creator_name: 'Space',
      prompt: 'LAND',
      init_room: 'space_lander_rm_lander',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'space_lander_sng_zandy_aliens_edit',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        0,
        214,
        179,
      ],
      cartridge_col_secondary: [
        0,
        125,
        150,
      ],
      cartridge_label: 'space_lander_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'space',
      ],
      date_added: '21/07/04',
    },
  },
  {
    name: 'space_scooter',
    config: {
      config_version: 1,
      game_name: 'Rixel Rider',
      creator_name: 'Space',
      prompt: 'Backflip',
      init_room: 'space_scoot_rm',
      view_width: 120,
      view_height: 80,
      time_seconds: 6,
      music_track: 'space_scooter_sng_meseta_midnight_drive',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        180,
        92,
        117,
      ],
      cartridge_col_secondary: [
        43,
        36,
        56,
      ],
      cartridge_label: 'space_scooter_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: [
        'space',
        'meseta',
        'freesound.org',
        'zapsplat.com',
      ],
      date_added: '21/07/12',
      is_enabled: true,
    },
  },
  {
    name: 'yosi_epic_fire_truck',
    config: {
      config_version: 1,
      game_name: 'Epic Fire Truck',
      creator_name: 'Yosi',
      prompt: 'MASH',
      init_room: 'yosi_EFT_rm_init',
      view_width: 240,
      view_height: 160,
      time_seconds: 10,
      music_track: 'yosi_EFT_song',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        255,
        50,
        50,
      ],
      cartridge_col_secondary: [
        50,
        50,
        255,
      ],
      cartridge_label: 'yosi_EFT_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'yosi',
      ],
      date_added: '21/07/08',
    },
  },
  {
    name: 'n8fl_reach_for_it_mister',
    config: {
      config_version: 1,
      game_name: 'Reach For It, Mister',
      creator_name: 'net8floz',
      prompt: 'Wait for it',
      init_room: 'n8fl_reach_for_it_mister_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 8,
      music_track: false,
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        89,
        62,
        71,
      ],
      cartridge_col_secondary: [
        122,
        88,
        89,
      ],
      cartridge_label: 'n8fl_reach_for_it_mister_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'net8floz',
        'meseta',
        'space',
      ],
      date_added: '21/07/05',
    },
  },
  {
    name: 'mimpy_dinner_date',
    config: {
      config_version: 1,
      game_name: 'Dinner Date',
      creator_name: 'Mimpy',
      prompt: 'REST',
      init_room: 'mimpy_duckdate_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'mimpy_duckdate_mus_hop',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        76,
        33,
        33,
      ],
      cartridge_col_secondary: [
        102,
        48,
        48,
      ],
      cartridge_label: 'mimpy_duckdate_label',
      default_is_fail: false,
      supports_difficulty_scaling: false,
      credits: [
        'Mimpy',
      ],
      date_added: '21/07/09',
    },
  },
  {
    name: 'mimpy_fire_alarm',
    config: {
      config_version: 1,
      game_name: 'Fire Alarm',
      creator_name: 'Mimpy',
      prompt: 'DOUSE',
      init_room: 'mimpy_firealarm_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'mimpy_firealarm_emergency',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        200,
        64,
        28,
      ],
      cartridge_col_secondary: [
        102,
        30,
        32,
      ],
      cartridge_label: 'mimpy_firealarm_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'Mimpy',
      ],
      date_added: '21/07/06',
    },
  },
  {
    name: 'baku_chug',
    config: {
      config_version: 1,
      game_name: 'Forced Choice of a New Generation',
      creator_name: 'baku',
      prompt: 'CHUG',
      init_room: 'baku_chug_rm',
      view_width: 160,
      view_height: 107,
      time_seconds: 7,
      music_track: 'sng_zandy_xylo',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        148,
        44,
        75,
      ],
      cartridge_col_secondary: [
        98,
        23,
        72,
      ],
      cartridge_label: 'baku_chug_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'baku',
      ],
      date_added: '21/07/08',
    },
  },
  {
    name: 'baku_mine',
    config: {
      config_version: 1,
      game_name: 'Lonesome Miner',
      creator_name: 'baku',
      prompt: [
        'MINE DIAMOND',
        'MINE EMERALD',
        'MINE GOLD',
        'MINE RUBY',
        'MINE IRON',
      ],
      init_room: 'baku_mine_rm',
      view_width: 480,
      view_height: 320,
      time_seconds: 12,
      music_track: 'baku_mine_bgm_minecraft',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        96,
        81,
        88,
      ],
      cartridge_col_secondary: [
        42,
        35,
        37,
      ],
      cartridge_label: 'baku_mine_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'baku',
        'meseta',
      ],
      date_added: '21/07/21',
    },
  },
  {
    name: 'anti_hats',
    config: {
      config_version: 1,
      game_name: 'Hats',
      creator_name: 'Antidissmist',
      prompt: 'SHADES',
      init_room: 'anti_hats_rm_start',
      view_width: 240,
      view_height: 160,
      time_seconds: 4,
      music_track: 'anti_hats_music',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        29,
        43,
        83,
      ],
      cartridge_col_secondary: [
        126,
        37,
        83,
      ],
      cartridge_label: 'anti_hats_sp_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'Antidissmist',
      ],
      date_added: '21/07/14',
    },
  },
  {
    name: 'tfg_collision',
    config: {
      config_version: 1,
      game_name: 'FIX COLLISION',
      creator_name: 'tfg',
      prompt: 'FIND ERROR',
      init_room: 'tfg_collision_rm_game',
      view_width: 960,
      view_height: 640,
      time_seconds: 9.5,
      music_track: 'sng_ennway_bit_battle',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: '0x121212',
      cartridge_col_secondary: '0x71b8ff',
      cartridge_label: 'tfg_collision_spr_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: [
        'tfg',
        'ennway',
        'zandy',
      ],
      date_added: '21/07/09',
    },
  },
  {
    name: 'tfg_swipe',
    config: {
      config_version: 1,
      game_name: 'SWIPE',
      creator_name: 'tfg',
      prompt: 'SWIPE',
      init_room: 'tfg_swipe_rm_game',
      view_width: -1,
      view_height: -1,
      time_seconds: 5,
      music_track: 'tfg_swipe_bgm_amogus',
      music_loops: false,
      interpolation_on: true,
      cartridge_col_primary: '0x555555',
      cartridge_col_secondary: '0x959595',
      cartridge_label: 'tfg_swipe_spr_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: [
        'tfg',
        'zandy',
        'space',
      ],
      date_added: '21/08/15',
      is_enabled: true,
    },
  },
  {
    name: 'nahoo_beenade',
    config: {
      config_version: 1,
      game_name: 'Beenade',
      creator_name: 'Nahoo',
      prompt: 'POLLINATE',
      init_room: 'nahoo_beenade_rMain',
      is_enabled: true,
      view_width: 480,
      view_height: 320,
      time_seconds: 5,
      music_track: 'Nahoo_mMain',
      music_loops: true,
      interpolation_on: false,
      cartridge_col_primary: [
        255,
        244,
        101,
      ],
      cartridge_col_secondary: [
        241,
        161,
        96,
      ],
      cartridge_label: 'Nahoo_beenade_cartridge',
      default_is_fail: true,
      supports_difficulty_scaling: false,
      credits: [
        'Nahoo',
      ],
      date_added: '21/07/04',
    },
  },
  {
    name: 'jdllama_hammer',
    config: {
      config_version: 1,
      game_name: "THROWIN' THE HAMMER",
      is_enabled: true,
      creator_name: 'J.D. Lowe',
      prompt: 'THROW HAMMER',
      init_room: 'jdllama_hammer_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'noone',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        0,
        0,
        0,
      ],
      cartridge_col_secondary: [
        131,
        147,
        202,
      ],
      cartridge_label: 'jdllama_hammer_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'J.D. Lowe',
      ],
      date_added: '21/08/12',
    },
  },
  {
    name: 'jdllama_target',
    config: {
      config_version: 1,
      game_name: 'TARGET BREAKING YEAH',
      creator_name: 'J.D. Lowe',
      prompt: 'SHOOT THE TARGETS',
      init_room: 'jdllama_target_rm',
      view_width: 240,
      view_height: 160,
      time_seconds: 5,
      music_track: 'jdllama_target_snd_theme',
      music_loops: false,
      interpolation_on: false,
      cartridge_col_primary: [
        0,
        0,
        0,
      ],
      cartridge_col_secondary: [
        55,
        255,
        255,
      ],
      cartridge_label: 'jdllama_target_spr_label',
      default_is_fail: true,
      supports_difficulty_scaling: true,
      credits: [
        'J.D. Lowe',
        'Zandy',
      ],
      date_added: '21/08/09',
    },
  },
];
export const numGames = 17;
export const numContributors = 19;
