/// @desc Draw the title screen.
var cam = KATSAII_WITCH_WANDA_VIEW_CAM;
var cam_left = camera_get_view_x(cam);
var cam_top = camera_get_view_y(cam);
var cam_right = cam_left + camera_get_view_width(cam);
var cam_bottom = cam_top + camera_get_view_height(cam);
var cam_xcentre = mean(cam_left, cam_right);
if not (surface_exists(titleSurface)) {
    titleSurface = surface_create(cam_right - cam_left, cam_bottom - cam_top);
}
var primary = JAM_COLOUR_BLEND;
var secondary = JamCRed.FORREST_FIRE;
draw_set_alpha(min(1, 4 * musicFade));
//draw_set_colour(primary);
draw_set_valign(fa_middle);
draw_set_halign(fa_center);
//draw_set_colour(selection == 2 ? secondary : primary);
//jam_draw_text_wonky(cam_xcentre - 60, cam_top + 20, "Katsaii");
//draw_set_colour(primary);
//jam_draw_text_wonky(cam_xcentre - 20, cam_top + 20, "&");
//draw_set_colour(selection == 3 ? secondary : primary);
//jam_draw_text_wonky(cam_xcentre + 50, cam_top + 20, "Mashmerlow");
//jam_draw_text_wonky(cam_xcentre - 60, cam_top + 20, "Move\nWASD or Arrows");
//jam_draw_text_wonky(cam_left + 60, cam_bottom - 85, "Fullscreen\nF11");
//jam_draw_text_wonky(cam_xcentre + 50, cam_top + 20, "Shoot\nEnter or X");
//jam_draw_text_wonky(cam_right - 60, cam_bottom - 85, "Pixel-Perfect\nF12");
draw_set_font(jam_fnt_default);
draw_set_colour(primary);
draw_text(cam_xcentre, cam_top + 15, "DIFFICULTY");
var diff_radius = string_width("DIFFICULTY") div 2 + 4 + round(2 * sin(current_time * 0.0035));
draw_sprite_ext(jam_spr_arrow, 0, cam_xcentre - diff_radius - 1, cam_top + 14, -1, 1, 0, selection == 2 ? secondary : primary, draw_get_alpha());
draw_sprite_ext(jam_spr_arrow, 0, cam_xcentre + diff_radius, cam_top + 14, 1, 1, 0, selection == 3 ? secondary : primary, draw_get_alpha());
var diff_colour = difficultyLevels[global.jamCurrentDifficultyLevelID + 1];
var diff_colour2 = difficultyLevels[global.jamCurrentDifficultyLevelID + 3];
var diff_caption = difficultyLevels[global.jamCurrentDifficultyLevelID + 2];
var diff_caption_x = KATSAII_WITCH_WANDA_VIEW_CENTRE_X;
var band_mid = cam_top + 30;
var band_top = band_mid - 6;
var band_bottom = band_mid + 4;
draw_set_colour(diff_colour);
draw_rectangle(cam_left, band_top, cam_right, band_bottom, false);
draw_set_colour(diff_colour2);
draw_text(diff_caption_x, band_mid, diff_caption);
gpu_set_blendmode(bm_add);
var sheen_width = sprite_get_width(jam_spr_sheen);
var sheen_left = cam_left - sheen_width;
var sheen_right = cam_right + sheen_width;
for (var i = sheen_left; i < sheen_right; i += sheen_width) {
    var sheen_offset = floor(current_time * 0.02) % sheen_width;
    draw_sprite(jam_spr_sheen, 0, i + sheen_offset, band_top);
}
gpu_set_blendmode(bm_normal);
//difficultyLevels
draw_set_colour(c_white);
surface_set_target(titleSurface);
draw_clear_alpha(c_black, 0);
draw_set_font(jam_fnt_tiny);
jam_draw_text_3d(cam_xcentre, cam_top + 105, "The Post-Jam Version", 6, make_colour_rgb(56, 166, 118), JamCYellow.REKINDLED);
draw_set_font(jam_fnt_script);
jam_draw_text_3d(cam_xcentre, cam_top + 80, "Witch Wanda", 12, secondary, make_colour_rgb(227, 200, 100));
surface_reset_target();
var tex = surface_get_texture(titleSurface);
shader_set_effect_outline(texture_get_texel_width(tex), texture_get_texel_height(tex), primary, 2);
draw_surface(titleSurface, cam_left, cam_top);
shader_reset();
draw_set_font(jam_fnt_tiny);
draw_set_colour(primary);
jam_draw_text_wonky(cam_xcentre, cam_bottom - 20, "High Score: " + string(global.jamHighScore));
draw_set_font(jam_fnt_complementary);
var option = lerp(cam_top, cam_bottom, optionThreshold);
draw_set_colour(selection == 0 ? secondary : primary);
jam_draw_text_wonky(cam_xcentre, option - 30, "Start");
draw_set_colour(selection == 1 ? secondary : primary);
jam_draw_text_wonky(cam_xcentre, option + 10, "Exit Jam");
draw_set_alpha(1.0);