//# ALLOW banned-functions
function ___init_metadata(){
//# WARN banned-functions
	
	// ---------------------------------------------------------------------------------------------------------------
	SET_TEST_VARS {
		test_mode_on: false,  // Default false | Whether or not to run the game in test mode
		microgame_key: "",    // Default ""    | The key for your game, as a string. ("key" meaning the property name for your game in the metadata)
		loop_game: true,     // Default false | Whether or not to instantly restart the test microgame when it ends
		difficulty_level: 1,  // Default 1     | The difficulty level to run the test at (1-5). 
		mute_test: false,     // Default false | if true, mutes all audio when running the game in test mode
							  // You can access the difficutly level in your game using the "DIFFICULTY" var.
	} return {
	// please set these values back to the defaults before you submit your game
	// ---------------------------------------------------------------------------------------------------------------


	/* TEMPLATE:
	(check the microgame_metadata_help file for more info on what these properties do)
	
	 (creator) game name
	johndoe_examplegame: {
		game_name: "Example Game",
		creator_name: "john doe",
		prompt: "SHOOT",
		init_room: johndoe_examplegame_rm_init,
		view_width: 240,
		view_height: 160,
		time_seconds: 5,
		music_track: noone,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(0, 0, 0),
		cartridge_col_secondary: make_color_rgb(255, 255, 255),
		cartridge_label: johndoe_examplegame_spr_label,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["john doe", "jane doe"],
		date_added: "YY/MM/DD",
	},
	*/
	
	space_rocket_lander: {
		game_name: "Rocket Lander",
		creator_name: "Space",
		prompt: "LAND",
		init_room: space_lander_rm_lander,
		view_width: 240,
		view_height: 160,
		time_seconds: 5,
		music_track: space_lander_sng_zandy_aliens_edit,
		music_loops: false,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(0, 214, 179),
		cartridge_col_secondary: make_color_rgb(0, 125, 150),
		cartridge_label: space_lander_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["space"],
		date_added: "21/07/05",
	},
	nahoo_beenade: {
		game_name: "Beenade",
		creator_name: "Nahoo",
		prompt: "POLLINATE",
		init_room: nahoo_beenade_rMain,
		view_width: 480,
		view_height: 320,
		time_seconds: 5,
		music_track: Nahoo_mMain,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_colour_rgb(255, 244, 101), //make_colour_rgb(93, 128, 54),
		cartridge_col_secondary: make_colour_rgb(241, 161, 96), //make_colour_rgb(239, 94, 255),
		cartridge_label: Nahoo_beenade_cartridge,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["Nahoo"],
		date_added: "21/07/05"
	},
	n8fl_penguin_blast: {
		game_name: "Penguin Blast",
		creator_name: "net8floz",
		prompt: "Don't Get Blasted",
		init_room: n8fl_penguin_blast_rm,
		view_width: 240,
		view_height: 160,
		time_seconds: 8,
		music_track: sng_zandy_woodblocks,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(255, 255, 255),
		cartridge_col_secondary: make_color_rgb(243, 122, 97),
		cartridge_label: n8fl_penguin_blast_label,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["net8floz"],
		date_added: "21/07/05",
	},
	n8fl_reach_for_it_mister: {
		game_name: "Reach For It, Mister",
		creator_name: "net8floz",
		prompt: "Wait for it",
		init_room: n8fl_reach_for_it_mister_rm,
		view_width: 240,
		view_height: 160,
		time_seconds: 8,
		music_track: noone,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(89, 62, 71),
		cartridge_col_secondary: make_color_rgb(122, 88, 89),
		cartridge_label: n8fl_reach_for_it_mister_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["net8floz", "meseta", "space"],
		date_added: "21/07/05",
	},
	n8fl_admin_simulator: {
		// sound fx : https://mixkit.co/free-sound-effects/hit/
		game_name: "GM Admin Simulator",
		creator_name: "net8floz",
		prompt: "BAN OR BE BANNED",
		init_room: n8fl_admin_simulator_rm,
		view_width: 240,
		view_height: 160,
		time_seconds: 6,
		music_track: n8fl_admin_simulator_music,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(89, 62, 71),
		cartridge_col_secondary: make_color_rgb(122, 88, 89),
		cartridge_label: n8fl_admin_simulator_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["net8floz", "meseta", "space", "mixkit.c"],
		date_added: "21/07/07",
	},
	n8fl_escape1: {
		// sound fx : https://mixkit.co/free-sound-effects/hit/
		game_name: "Action Escape Pt 1",
		creator_name: "net8floz",
		prompt: "Jump On The Car",
		init_room: n8fl_escape1_rm,
		view_width: 120,
		view_height: 80,
		time_seconds: 5,
		music_track: n8fl_escape1_music,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(89, 62, 71),
		cartridge_col_secondary: make_color_rgb(122, 88, 89),
		cartridge_label: n8fl_escape1_label,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["net8floz", "meseta", "space", "mixkit.c"],
		date_added: "21/07/07",
	},

	yosi_epic_fire_truck: {
		game_name: "Epic Fire Truck",
		creator_name: "Yosi",
		prompt: "MASH",
		init_room: yosi_EFT_rm_init,
		view_width: 240,
		view_height: 160,
		time_seconds: 10,
		music_track: yosi_EFT_song,
		music_loops: false,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(255, 50, 50),
		cartridge_col_secondary: make_color_rgb(50, 50, 255),
		cartridge_label: yosi_EFT_spr_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["yosi"],
		date_added: "21/07/08",
	},
	//n8fl_escape2: {
	//	// sound fx : https://mixkit.co/free-sound-effects/hit/
	//	game_name: "Action Escape Pt 2",
	//	creator_name: "net8floz",
	//	prompt: "Jump On The Train",
	//	init_room: n8fl_escape2_rm,
	//	view_width: 120,
	//	view_height: 80,
	//	time_seconds: 5,
	//	music_track: sng_zandy_woodblocks,
	//	music_loops: true,
	//	interpolation_on: false,
	//	cartridge_col_primary: make_color_rgb(89, 62, 71),
	//	cartridge_col_secondary: make_color_rgb(122, 88, 89),
	//	cartridge_label: n8fl_escape2_label,
	//	default_is_fail: true,
	//	supports_difficulty_scaling: false,
	//	credits: ["net8floz", "meseta", "space", "mixkit.c"],
	//	date_added: "21/07/07",
	//},

	n8fl_escape2: {
		// sound fx : https://mixkit.co/free-sound-effects/hit/
		game_name: "Action Escape Pt 2",
		creator_name: "net8floz",
		prompt: "Jump On The Train",
		init_room: n8fl_escape2_rm,
		view_width: 120,
		view_height: 80,
		time_seconds: 5,
		music_track: n8fl_escape1_music,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(89, 62, 71),
		cartridge_col_secondary: make_color_rgb(122, 88, 89),
		cartridge_label: n8fl_escape2_label,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["net8floz", "meseta", "space", "mixkit.c"],
		date_added: "21/07/07",
	},
	n8fl_escape3: {
		// sound fx : https://mixkit.co/free-sound-effects/hit/
		game_name: "Action Escape Pt 3",
		creator_name: "net8floz",
		prompt: "Jump On The Train",
		init_room: n8fl_escape3_rm,
		view_width: 120,
		view_height: 80,
		time_seconds: 5,
		music_track: n8fl_escape1_music,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(89, 62, 71),
		cartridge_col_secondary: make_color_rgb(122, 88, 89),
		cartridge_label: n8fl_escape3_label,
		default_is_fail: true,
		supports_difficulty_scaling: false,
		credits: ["net8floz", "meseta", "space", "mixkit.c"],
		date_added: "21/07/07",
	},
	//n8fl_ice_broom: {
	//	game_name: "Ice Broom",
	//	creator_name: "net8floz",
	//	prompt: "Shuffle",
	//	init_room: n8fl_ice_broom_rm,
	//	view_width: 240,
	//	view_height: 160,
	//	time_seconds: 5,
	//	music_track: sng_zandy_descending,
	//	music_loops: true,
	//	interpolation_on: false,
	//	cartridge_col_primary: make_color_rgb(89, 62, 71),
	//	cartridge_col_secondary: make_color_rgb(122, 88, 89),
	//	cartridge_label: n8fl_reach_for_it_mister_label,
	//	default_is_fail: true,
	//	supports_difficulty_scaling: true,
	//	credits: ["net8floz"],
	//	date_added: "21/07/05",
	//},

	
	

	/* sidorakh_controller_tester: {
		game_name: "Controller Tester",
		creator_name: "Sidorakh",
		prompt: "TEST",
		init_room: sid_controller_tester_room,
		view_width: 240,
		view_height: 160,
		time_seconds: 5,
		music_track: noone,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(0, 0, 0),
		cartridge_col_secondary: make_color_rgb(255, 255, 255),
		cartridge_label: johndoe_examplegame_spr_label,
		default_is_fail: false,
		supports_difficulty_scaling: false,
		credits: ["Sidorakh", "NOT. MY. BIRTHDAY."],
		date_added: "21/07/07",
	},*/
	mimpy_firealarm: {
		game_name: "Fire Alarm",
		creator_name: "Mimpy",
		prompt: "DOUSE",
		init_room: mimpy_firealarm_rm,
		view_width: 240,
		view_height: 160,
		time_seconds: 5,
		music_track: sng_ennway_bit_battle,
		music_loops: true,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(200, 64, 28),
		cartridge_col_secondary: make_color_rgb(102, 30, 32),
		cartridge_label: mimpy_firealarm_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["Mimpy"],
		date_added: "21/07/06",
	},
	baku_chug: {
		game_name: "Forced Choice of a New Generation",
		creator_name: "baku",
		prompt: "CHUG",
		init_room: baku_chug_rm,
		view_width: 160,
		view_height: 107,
		time_seconds: 7,
		music_track: sng_zandy_xylo,
		music_loops: false,
		interpolation_on: false,
		cartridge_col_primary: make_color_rgb(148, 44, 75),
		cartridge_col_secondary: make_color_rgb(98, 23, 72),
		cartridge_label: baku_chug_spr_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["baku"],
		date_added: "21/08/07",
	},
	katsaii_witchwanda: {
		game_name: "Witch Wanda",
		creator_name: "Katsaii & Mashmerlow",
		prompt: "CRAFT",
		init_room: katsaii_witchwanda_rm,
		view_width: 1,
		view_height: 1,
		time_seconds: 6,
		music_track: katsaii_witchwanda_mu,
		music_loops: false,
		interpolation_on: true,
		cartridge_col_primary: make_color_rgb(148, 44, 75),
		cartridge_col_secondary: make_color_rgb(98, 23, 72),
		cartridge_label: katsaii_witchwanda_label,
		default_is_fail: true,
		supports_difficulty_scaling: true,
		credits: ["Katsaii", "Mashmerlow"],
		date_added: "21/07/09",
	},
}}
