microgame_register("tfg_collision", {
    config_version: 1,
    game_name: "Fix Collision",
    authors : "tfg",
    prompt: "FIND ERROR",
    init_room: tfg_collision_rm_game,
    view_width: 960,
    view_height: 640,
    time_seconds: 9.5,
    music_track: sng_ennway_bit_battle,
    music_loops: false,
    interpolation_on: false,
    cartridge_col_primary: "0x121212",
    cartridge_col_secondary: "0xffb871",
    cartridge_label: tfg_collision_spr_cartridge,
    default_is_fail: true,
    supports_difficulty_scaling: false,
    credits: ["tfg", "ennway", "zandy"],
    date_added: {
		day: 9,
		month: 7,
		year: 21,
	},
	is_enabled: true,
	supports_html: true,
	supports_pi: true,
	show_on_website: true,
});

microgame_register("tfg_swipe", {
    config_version: 1,
    game_name: "Swipe",
    authors : "tfg",
    prompt: "SWIPE",
    init_room: tfg_swipe_rm_game,
    view_width: -1,
    view_height: -1,
    time_seconds: 5,
    music_track: tfg_swipe_bgm_amogus,
    music_loops: false,
    interpolation_on: true,
    cartridge_col_primary: "0x555555",
    cartridge_col_secondary: "0x959595",
    cartridge_label: tfg_swipe_spr_cartridge,
    default_is_fail: true,
    supports_difficulty_scaling: true,
    credits: ["tfg", "zandy", "space"],
    date_added: "21/08/15",
	is_enabled: true,
	supports_html: true,
	supports_pi: true,
	show_on_website: true,
});

microgame_register("tfg_guess", {
    config_version: 1,
    game_name: "Locate",
    authors : "tfg",
    prompt: "LOCATE",
    init_room: tfg_guess_rm_game,
    view_width: -1,
    view_height: -1,
    time_seconds: 10,
    music_track: sng_zandy_koto,
    music_loops: true,
    interpolation_on: false,
    cartridge_col_primary: "0x62b4de",
    cartridge_col_secondary: "0xcbf5ef",
    cartridge_label: tfg_guess_spr_cartridge,
    default_is_fail: true,
    supports_difficulty_scaling: true,
    credits: ["tfg", "space", "zandy"],
    date_added: {
		day: 16,
		month: 1,
		year: 22,
	},
	is_enabled: true,
	supports_html: true,
	supports_pi: true,
	show_on_website: true,
});